window.CONFIG = {
    FILL_LIMIT: 20,
    MAX_ACTIVE: 5,
    SEEDING_DURATION: 120000,
    UPDATE_INTERVAL: 500,
    STATS_INTERVAL: 1000,
    DEFAULT_THEME: 'dark',
    MIN_SIZE_GB: 1.0,
    MAX_SIZE_GB: 10.0,
    MAX_GLOBAL_DOWNLOAD_MBPS: 0,
    MAX_GLOBAL_UPLOAD_MBPS: 0,
    IS_CALIBRATED: false
};