window.CONFIG = {
    FILL_LIMIT: 20,
    MAX_ACTIVE: 4,
    SEEDING_DURATION: 480000,
    UPDATE_INTERVAL: 500,
    STATS_INTERVAL: 2000,
    DEFAULT_THEME: 'dark',
    MIN_SIZE_GB: 4.0,
    MAX_SIZE_GB: 10.0,
    MAX_GLOBAL_DOWNLOAD_MBPS: 0,
    MAX_GLOBAL_UPLOAD_MBPS: 0,
    IS_CALIBRATED: false
};
